# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Hulu, Mouse36872, wiki]
patreon: # Replace with a single Patreon username go
open_collective: # Replace with a single Open Collective username Tornado.io
ko_fi: # Replace with a single Ko-fi username 35
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username NOgo
issuehunt: # Replace with a single IssueHunt username SP
otechie: # Replace with a single Otechie username BK
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://wish.com','https://goarmy.com' 'https://xboxlive.com, 'https://aspca.org' 'https://luvs.com']
